# install with `conda env create -f environment.yml`

name: ssnz
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - notebook
  - numpy
  - pandas
  - xarray
  - matplotlib
  - cartopy
  - plotly
  - panel
  - scikit-learn
  - scipy
  - pip
  - pip:
    - progressbar2
    - jupyter-book
    - cookiecutter
    - pytest
    - black
    - sphinx-thebe
    - netcdf4
    - zarr
    - great_circle_calculator
    - geopy